import { config } from '../config.js'

// AI provider seam (Vol 3 model strategy / Vol 4 AI platform). The rest of the
// system depends only on this interface, so a real Azure OpenAI deployment can
// replace the mock without any change to business logic or the API surface.
export interface ChatMessage {
  role: 'system' | 'user' | 'assistant'
  content: string
}

export interface AiProvider {
  readonly name: string
  complete(messages: ChatMessage[]): Promise<string>
}

/**
 * Deterministic, offline provider so the whole system runs with zero credentials.
 * It performs light template reasoning rather than calling a model.
 */
export class MockAiProvider implements AiProvider {
  readonly name = 'mock'
  async complete(messages: ChatMessage[]): Promise<string> {
    const last = messages.at(-1)?.content ?? ''
    return `[[mock-model]] Acknowledged: "${last.slice(0, 120)}". In production this response is generated by Azure OpenAI (${config.ai.azureDeployment}).`
  }
}

/**
 * Real Azure OpenAI provider. Left un-credentialled by design; it activates only
 * when EIOS_AI_PROVIDER=azure-openai and the endpoint/key are configured. Uses the
 * Chat Completions REST contract so it needs no extra SDK dependency.
 */
export class AzureOpenAiProvider implements AiProvider {
  readonly name = 'azure-openai'
  async complete(messages: ChatMessage[]): Promise<string> {
    const { azureEndpoint, azureApiKey, azureDeployment } = config.ai
    if (!azureEndpoint || !azureApiKey) {
      throw new Error('Azure OpenAI not configured: set AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_API_KEY')
    }
    const url = `${azureEndpoint.replace(/\/$/, '')}/openai/deployments/${azureDeployment}/chat/completions?api-version=2024-06-01`
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'api-key': azureApiKey },
      body: JSON.stringify({ messages, temperature: 0.2, max_tokens: 800 }),
    })
    if (!res.ok) throw new Error(`Azure OpenAI error ${res.status}: ${await res.text()}`)
    const data = (await res.json()) as { choices: { message: { content: string } }[] }
    return data.choices[0]?.message?.content ?? ''
  }
}

export function createAiProvider(): AiProvider {
  return config.ai.provider === 'azure-openai' ? new AzureOpenAiProvider() : new MockAiProvider()
}

export const aiProvider = createAiProvider()
